- .run/ignite3 load workloada (127.0.0.1).run.xml
- .run/ignite3 run workloada (127.0.0.1).run.xml
- bin/ycsb.bat
- ignite3/pom.xml
First part of https://ggsystems.atlassian.net/browse/QA-4139
- fixed bat file and pom.xml
- added run configuration examples
> QA-4139 Fixes for bat file and pom.xml

- ignite/pom.xml
- ignite3/pom.xml
- pom.xml
https://ggsystems.atlassian.net/browse/QA-4256
> QA-4256 Change GridGain version for ignite-binding module

- ignite/pom.xml
- ignite/src/main/java/site/ycsb/db/ignite/IgniteAbstractClient.java
- ignite/src/main/java/site/ycsb/db/ignite/IgniteClient.java
- ignite/src/main/java/site/ycsb/db/ignite/IgniteSqlClient.java
- ignite/src/main/resources/emb-kv-atomic.xml
- ignite/src/main/resources/emb-kv-tx.xml
- ignite/src/main/resources/emb-sql-atomic.xml
- ignite/src/main/resources/emb-sql-tx.xml
https://ggsystems.atlassian.net/browse/QA-4279
> QA-4279 [YCSB] Embedded mode for AI2/GG8 benchmarks

- checkstyle.xml
- core/src/main/java/site/ycsb/Client.java
- core/src/main/java/site/ycsb/ClientThread.java
- core/src/main/java/site/ycsb/DBWrapper.java
- core/src/main/java/site/ycsb/StatusThread.java
- core/src/main/java/site/ycsb/measurements/Measurements.java
- core/src/main/java/site/ycsb/workloads/CoreWorkload.java
https://ggsystems.atlassian.net/browse/QA-4315
Ward report example - https://ward.gridgain.com/tests/653a2774165f80acb1d40954
> QA-4315 [YCSB] Introduce a warmup parameter

- ignite3/pom.xml
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteAbstractClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteStreamerClient.java
https://ggsystems.atlassian.net/browse/QA-4408
- Needs Java 9 language level according to [doc](https://docs.google.com/document/d/19pg73e3GQpo-vYmXVlB9mhGvehvSRH8BXYjvU5RR-_o/edit#heading=h.hx3lrtv8l2b4)
- Report example - https://ward.gridgain.com/tests/6560a2ee3659a30406bb48e8
> QA-4408 [YCSB][AI3] Support DataStreamer for data preloading

- ignite3/src/main/java/site/ycsb/db/ignite3/AbstractSqlClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteJdbcClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteSqlClient.java
https://ggsystems.atlassian.net/browse/QA-4404
> QA-4404 [YCSB] Prefer prepared statements for DML in sql clients

- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteSqlClient.java
https://ggsystems.atlassian.net/browse/QA-4556
> QA-4556 [YCSB] Use execute with Statement for IgniteSqlClient

- ignite/src/main/java/site/ycsb/db/ignite/IgniteAbstractClient.java
https://ggsystems.atlassian.net/browse/QA-4597
> QA-4597 [YCSB] Support multi node runs for AI2/GG8

- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteStreamerClient.java
Fix due to renaming batchSize to pageSize in AI3
https://github.com/apache/ignite-3/pull/3072
https://ggsystems.atlassian.net/browse/IGN-23409
> fix after renaming from batchSize to pageSize in AI3

- ignite/src/main/java/site/ycsb/db/ignite/IgniteAbstractClient.java
- ignite/src/main/java/site/ycsb/db/ignite/IgniteJdbcClient.java
- ignite/src/main/resources/emb-jdbc.xml
- ignite3/src/main/java/site/ycsb/db/ignite3/AbstractSqlClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteJdbcClient.java
https://ggsystems.atlassian.net/browse/QA-4595
> QA-4595 [YCSB] Add JDBC client mode for AI2/GG8

- ignite/src/main/java/site/ycsb/db/ignite/IgniteAbstractClient.java
Follow up on https://github.com/gridgain/YCSB/pull/25
> QA-4595 minor comment fix

- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteStreamerClient.java
**What was done**
- Fixed `IgniteStreamerClient` after changes made in [IGNITE-21403](https://ggsystems.atlassian.net/browse/IGN-23712)
**Issue details:**
🟢 Successful [test run on Feb 14, 2024](https://ward.gridgain.com/tests/65cc43cc565f06dd3625cd05) on commit [e521574](https://github.com/apache/ignite-3/commit/e521574594d35405b2c0c9bfab8e5c44bcc14c4c)
🔴 Failed [test run on Feb 15, 2024](https://ward.gridgain.com/tests/65cd951e565f06dd3625db74) on commit [231593e](https://github.com/apache/ignite-3/commit/231593e94b4d20985b31445042f26391f0fa7d30)
Starting from Feb 15, 2024 we got the following exception in DataStreamer runs for YCSB
```
site.ycsb.DBException: java.util.concurrent.CompletionException: java.lang.ClassCastException: class org.apache.ignite.table.TupleImpl cannot be cast to …
```
> Fix IgniteStreamerClient after IGNITE-21403

- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteAbstractClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteSqlClient.java
https://ggsystems.atlassian.net/browse/QA-4777
> QA-4777 [YCSB] Migrate from Session to direct IgniteSql usage in AI3 SQL API

- ignite/src/main/java/site/ycsb/db/ignite/IgniteAbstractClient.java
- ignite/src/main/java/site/ycsb/db/ignite/IgniteClient.java
- ignite/src/main/java/site/ycsb/db/ignite/IgniteJdbcClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteJdbcClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteSqlClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteStreamerClient.java
https://ggsystems.atlassian.net/browse/QA-4797
> QA-4797 [YCSB][GG8] Implement key-value putAll()/getAll() benchmark

- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteAbstractClient.java
- ignite3/src/main/resources/ignite-config-nofsync.json
- ignite3/src/main/resources/ignite-config.json
https://ggsystems.atlassian.net/browse/QA-4833
Test run example: https://ward.gridgain.com/tests/6619604c1570869f793d1b10
> QA-4833 [YCSB] Handle migration to storage profiles

- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteParam.java
IgniteParam class has checkstyle issues currently and the YCSB can't be released.
> QA-4823 Fixes checkstyle issues for IgniteParam class

- core/src/main/java/site/ycsb/ClientThread.java
- core/src/main/java/site/ycsb/Workload.java
- core/src/main/java/site/ycsb/workloads/CoreWorkload.java
- core/src/main/java/site/ycsb/workloads/CoreWorkloadThreadState.java
- core/src/main/java/site/ycsb/workloads/RestWorkload.java
- core/src/main/java/site/ycsb/workloads/TimeSeriesWorkload.java
- core/src/test/java/site/ycsb/workloads/TestTimeSeriesWorkload.java
https://ggsystems.atlassian.net/browse/QA-4730
> QA-4730 [YCSB][AI3] Rework batch runs with multi-threaded mode

- ignite3/src/main/resources/ignite-config-aimem.json
- ignite3/src/main/resources/ignite-config-aipersist.json
- ignite3/src/main/resources/ignite-config-nofsync-aimem.json
- ignite3/src/main/resources/ignite-config-nofsync-aipersist.json
- ignite3/src/main/resources/ignite-config-nofsync-rocksdb.json
- ignite3/src/main/resources/ignite-config-rocksdb.json
https://ggsystems.atlassian.net/browse/QA-5040
> QA-5040 [YCSB] Fix using storage profile/engine for embedded mode

- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteAbstractClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteJdbcClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteSqlClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteStreamerClient.java
https://ggsystems.atlassian.net/browse/QA-5022
https://issues.apache.org/jira/browse/IGNITE-22224
❗ Needs https://github.com/ggprivate/poc-tester/pull/695 merged before this
Test runs on a local machine with https://github.com/ggprivate/poc-tester/pull/695:
- 🟢 KV embedded - https://ward.gridgain.com/tests/667d62c86309fe0ea15c34fb
- 🟢 SQL embedded - https://ward.gridgain.com/tests/667d63cf6309fe0ea15c3662
- 🟢 JDBC embedded - https://ward.gridgain.com/tests/667d60986309fe0ea15c3304
> QA-5022 [YCSB] Adapt to changes in IGNITE-22224

- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteSqlClient.java
https://ggsystems.atlassian.net/browse/QA-5110
> QA-5110 [YCSB] Handle IGNITE-22611 (Statement is not AutoClosable)

- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteStreamerClient.java
https://ggsystems.atlassian.net/browse/QA-5311
> QA-5311 [YCSB] Adapt to breaking change in IGNITE-23026 (DS API)

- core/src/main/java/site/ycsb/Client.java
- ignite/src/main/java/site/ycsb/db/ignite/IgniteAbstractClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteAbstractClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteParam.java
- ignite3/src/main/resources/ignite-config-aimem.json
- ignite3/src/main/resources/ignite-config-aipersist.json
- ignite3/src/main/resources/ignite-config-nofsync-aimem.json
- ignite3/src/main/resources/ignite-config-nofsync-aipersist.json
- ignite3/src/main/resources/ignite-config-nofsync-rocksdb.json
- ignite3/src/main/resources/ignite-config-nofsync.json
- ignite3/src/main/resources/ignite-config-rocksdb.json
- ignite3/src/main/resources/ignite-config.json
- add 'shutdownIgnite' parameter for externally provided Ignite instance
- update ignite-config with 'ignite' root wrapper
- support 'b' postfix as billion modifier
> QA-5361 Add 'shutdownIgnite' parameter for externally provided Ignite instance

- ignite3/README.md
- ignite3/pom.xml
- ignite3/src/main/java/site/ycsb/db/ignite3/AbstractSqlClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteAbstractClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteJdbcClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteSqlClient.java
- ignite3/src/test/java/site/ycsb/db/ignite3/IgniteAbstractClientTest.java
https://ward.gridgain.com/tests/672b9822cbbc295a2bce166d
Sucessfull local run with AI3: [WARD](https://ward.gridgain.com/tests/672b9afacbbc295a2bce167a)
> QA-5531 Update create table syntax, add test for AbstractSqlClient

- ignite/src/main/java/site/ycsb/db/ignite/IgniteAbstractClient.java
- ignite/src/main/java/site/ycsb/db/ignite/IgniteClient.java
- ignite/src/main/java/site/ycsb/db/ignite/IgniteJdbcClient.java
- ignite/src/main/java/site/ycsb/db/ignite/IgniteSqlClient.java
- ignite/src/main/java/site/ycsb/db/ignite/IgniteTxJdbcClient.java
- ignite/src/main/java/site/ycsb/db/ignite/IgniteTxKvClient.java
- ignite/src/main/java/site/ycsb/db/ignite/IgniteTxSqlClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/AbstractSqlClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteAbstractClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteCriteriaClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteJdbcClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteParam.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteSqlClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteTxJdbcClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteTxKvClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteTxSqlClient.java
- implemented i2 Tx clients
- added ability to set 'txconcurrency' and 'txisolation' for i2 Tx clients
- added ability to set RO transactions with 'txreadonly' for i3 Tx clients
✔️ [Test run with TxKV](https://ggtc.gridgain.com/buildConfiguration/Qa_PocBenchmarkLabGg8BuildType/13209476)
> QA-5729 [YCSB][GG8] Add ability to use implicit transactions

- core/src/main/java/site/ycsb/workloads/CoreWorkload.java
- ignite/src/main/java/site/ycsb/db/ignite/IgniteAbstractClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteAbstractClient.java
- added index creation for i2
- added ability to specify index type for i3
Test runs:
✅ [AI3 with sorted index](https://ggtc.gridgain.com/buildConfiguration/Qa_PocBenchmarkAwsDevelAi3BuildType/13346159)
✅ [AI3 with hash index](https://ggtc.gridgain.com/buildConfiguration/Qa_PocBenchmarkAwsDevelAi3BuildType/13346160)
✅ [GG8 with indexes](https://ggtc.gridgain.com/buildConfiguration/Qa_PocBenchmarkAwsGg8BuildType/13345975)
> QA-5732 [YCSB][GG8] Implement index creation

- ignite/pom.xml
- ignite3/pom.xml
- pom.xml
Slack thread:
https://gridgain.slack.com/archives/CC3RL20R2/p1736934506211339
Build:
✅ [#61](https://ggtc.gridgain.com/buildConfiguration/Qa_YcsbPerformRelease/13345885)
> QA-5778 [YCSB] Change maven repo to 'gg-nexus2-01.gridgain.com'

- core/src/main/java/site/ycsb/workloads/CoreWorkload.java
- ignite3/src/main/java/site/ycsb/db/ignite3/AbstractSqlClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteAbstractClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteCriteriaClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteJdbcClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteParam.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteStreamerClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteTxKvClient.java
- ignite3/src/test/java/site/ycsb/db/ignite3/IgniteAbstractClientTest.java
Test runs:
✅ 1 table (default) AI3 [#7832](https://ggtc.gridgain.com/buildConfiguration/Qa_PocBenchmarkAwsDevelAi3BuildType/13557649)
✅ 10 tables AI3 [#7831](https://ggtc.gridgain.com/buildConfiguration/Qa_PocBenchmarkAwsDevelAi3BuildType/13557320)
✅ 100 tables GG9 [#7](https://ggtc.gridgain.com/buildConfiguration/Qa_PocBenchmarkAwsGg9BuildType/13557322)
✅ 1000 tables GG9 [#8](https://ggtc.gridgain.com/buildConfiguration/Qa_PocBenchmarkAwsGg9BuildType/13557650)
> QA-5866 [YCSB] Implement ability to create many test tables

- ignite3/src/main/java/site/ycsb/db/ignite3/AbstractSqlClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteJdbcClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteSqlClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteTxJdbcClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteTxKvClient.java
- ignite3/src/main/java/site/ycsb/db/ignite3/IgniteTxSqlClient.java
Test runs:
- [SQL without PS](https://ggtc.gridgain.com/buildConfiguration/Qa_PocBenchmarkLabAi3SourcesQueuedBuildType/15108262?buildTab=artifacts#%2FQa_PocBenchmarkLabAi3SourcesQueuedBuildType-2816-9.1.127-SNAPSHOT.zip;%2FQa_PocBenchmarkLabAi3SourcesQueuedBuildType-2816-9.1.127-SNAPSHOT.zip!%2Flog-2025-07-17-10-17-58%2Fother%2F172.25.4.49%2Fycsb;%2FQa_PocBenchmarkLabAi3SourcesQueuedBuildType-2816-9.1.127-SNAPSHOT.zip!%2Flog-2025-07-17-10-17-58%2Fother%2F172.25.4.49)
[UPDATE], AvgLatency(us), [8594.769433149964](https://ggtc.gridgain.com/repository/download/Qa_PocBenchmarkLabAi3SourcesQueuedBuildType/15108262:id/Qa_PocBenchmarkLabAi3SourcesQueuedBuildType-2816-9.1.127-SNAPSHOT.zip!/log-2025-07-17-10-17-58/other/172.25.4.49/ycsb/2025-07-17-10-14-01_172.25.4.49_sql_run.txt)
- [SQL with …
> QA-6119 Implement "update" action for ignite3 module
